import sys
import torch
import librosa
import numpy as np
import matplotlib.pyplot as plt
from transformers import AutoProcessor

MODEL_PATH = "/data/mg546924/models/Qwen2-Audio-7B-Instruct"
# Pick the FIRST chunk file generated by our newly generated dataset!
AUDIO_PATH = "/data/mg546924/llm_beatmap_generator/sft_dataset_pixabay/audio/487408_None_000.wav"

try:
    print(f"Loading Qwen2-Audio Processor from {MODEL_PATH}...")
    processor = AutoProcessor.from_pretrained(MODEL_PATH)
except Exception as e:
    print(f"\n[ERROR] Failed to load processor. You must run this exactly ON YOUR CLUSTER where the {MODEL_PATH} model lives!")
    sys.exit(1)

print(f"Loading actual audio chunk from {AUDIO_PATH}...")
audio, sr = librosa.load(AUDIO_PATH, sr=processor.feature_extractor.sampling_rate)

print("\nExecuting Qwen's actual internal Processor...")
# This calculates exactly what Qwen2-Audio mathematically generates for its brain
inputs = processor(text="List the onsets", audios=[audio], return_tensors="pt")

# 'input_features' contains exactly the Mel Spectrogram array that Qwen sees!
input_features = inputs.input_features[0] # Shape is typically (128, seq_len)
print(f"\n✅ Bypassed Qwen! Extracted exact internal Mel Spectrogram tensor.")
print(f"The LLM literally \"sees\" a massive array of shape: {input_features.shape}")

print("\nPlotting Qwen's exact internal tensor array...")
# Convert from PyTorch to numpy map for matplotlib drawing
spectrogram_numpy = input_features.numpy()

plt.figure(figsize=(14, 5))
plt.imshow(spectrogram_numpy, aspect='auto', origin='lower', cmap='magma')
plt.colorbar(format='%+2.0f')
plt.title(f"The EXACT Mathematical Array Generated by Qwen2-Audio's Face (Shape: {input_features.shape})")
plt.xlabel("Time Frames (Audio Tokens fed into the LLM)")
plt.ylabel("Mel Frequency Bins (128 slices)")
plt.tight_layout()

output_file = "/data/mg546924/llm_beatmap_generator/qwen_internal_spectrogram.png"
plt.savefig(output_file, dpi=300)
print(f"\n=======================================================")
print(f"Saved exact Qwen internal spectrogram to {output_file}!")
print(f"Check your VS Code or terminal to open {output_file} and see the mathematical array exact as Qwen sees it!")
