#!/usr/bin/env python3
"""
train_hierarchical_mumu.py
==========================
Phase 3 of the Hierarchical Generation Architecture ("Director & Actor").

This script trains MuMu-LLaMA to act as the "Director" — predicting an ordered
sequence of topological cluster tokens (<|cluster_N|>) from a 5-second audio slice.

Key changes vs the standard train_mumu_5s_lora.py:
  1. Tokenizer Vocabulary Extension:
       - Loads cluster_to_patterns_tokens.txt (2,189 unique tokens)
       - Calls tokenizer.add_special_tokens() to inject them
       - Calls model.llama.resize_token_embeddings() to expand the embedding matrix
  2. Dataset wired to hierarchical_train.jsonl:
       - Input : 5-second .wav slice
       - Target: "<|cluster_8|> <|cluster_12|> <|cluster_4|>" (NOT raw arrows)
  3. Labels masked correctly so only the cluster sequence is trained, not the prompt.
  4. All other mechanics (optimizer, AMP, grad clip, epoch checkpoints) are identical
     to the original script so the Slurm setup doesn't need changing.
"""

import os
import sys
import json
import csv as csv_mod
import torch
import torchaudio
import numpy as np
from torch.utils.data import Dataset, DataLoader
from tqdm import tqdm

# ─── Paths (HPC) ──────────────────────────────────────────────────────────────
MUMU_ROOT    = "/data/mg546924/llm_beatmap_generator/MuMu-LLaMA/MuMu-LLaMA"
LLAMA_DIR    = "/data/mg546924/llm_beatmap_generator/MuMu-LLaMA/ckpts/LLaMA"
MUMU_CKPT    = "/data/mg546924/llm_beatmap_generator/MuMu-LLaMA/ckpts/MuMu-LLaMA-MusicGen/checkpoint.pth"

# ── Hierarchical dataset (generated by prepare_hierarchical_sft.py) ──
DATASET_JSONL   = "/data/mg546924/llm_beatmap_generator/hierarchical_sft_dataset/hierarchical_train.jsonl"

# ── Token list (generated by build_sub_decoder_dict.py) ──
TOKENS_TXT      = "/data/mg546924/llm_beatmap_generator/scripts/cluster_to_patterns_tokens.txt"

OUTPUT_DIR      = "/data/mg546924/models/mumu-hierarchical-director"

# ─── Hyperparameters ──────────────────────────────────────────────────────────
NUM_EPOCHS  = 5
LR          = 1e-4
BATCH_SIZE  = 1
MAX_WORDS   = 256    # Cluster sequences are short — no need for 512
SAMPLE_RATE = 24000  # MuMu-LLaMA expects 24kHz
# ──────────────────────────────────────────────────────────────────────────────

sys.path.insert(0, MUMU_ROOT)


def load_cluster_tokens(tokens_txt_path):
    """Read the list of <|cluster_N|> tokens generated by build_sub_decoder_dict.py."""
    if not os.path.exists(tokens_txt_path):
        raise FileNotFoundError(
            f"Token list not found at {tokens_txt_path}. "
            "Run scripts/build_sub_decoder_dict.py first."
        )
    with open(tokens_txt_path, "r") as f:
        tokens = [line.strip() for line in f if line.strip()]
    print(f"  Loaded {len(tokens)} cluster tokens from {tokens_txt_path}")
    return tokens


def extend_tokenizer_and_model(tokenizer, model, cluster_tokens):
    print("\n── Extending Tokenizer Vocabulary ──────────────────────────────")
    before = len(tokenizer)
    tokenizer.add_special_tokens({"additional_special_tokens": cluster_tokens})
    after  = len(tokenizer)
    added  = after - before
    print(f"  Tokenizer vocab: {before} → {after} (+{added} cluster tokens)")

    # Find the embedding layer dynamically
    if hasattr(model.llama, "model") and hasattr(model.llama.model, "embed_tokens"):
        embedding_layer = model.llama.model.embed_tokens
    elif hasattr(model.llama, "tok_embeddings"):
        embedding_layer = model.llama.tok_embeddings
    else:
        raise AttributeError("Could not find the embedding layer in model.llama")

    old_num_tokens, embed_dim = embedding_layer.weight.shape
    mean_embed = embedding_layer.weight.data.mean(dim=0, keepdim=True)

    # Recreate the embedding layer entirely
    import torch.nn as nn
    new_embeds = nn.Embedding(after, embed_dim)
    with torch.no_grad():
        # Copy the original LLaMA weights + the 8 [AUD] weights
        new_embeds.weight.data[:old_num_tokens] = embedding_layer.weight.data
        # Warm-start the new cluster token vectors with the matrix mean
        added_for_clusters = after - old_num_tokens
        new_embeds.weight.data[old_num_tokens:] = mean_embed.expand(added_for_clusters, -1)
    
    # Enable gradients on the new layer
    new_embeds.weight.requires_grad = True

    # Drop the new layer in place
    if hasattr(model.llama, "model") and hasattr(model.llama.model, "embed_tokens"):
        model.llama.model.embed_tokens = new_embeds
    else:
        model.llama.tok_embeddings = new_embeds

    # Also resize the output head, if it exists (for Fairscale/Meta architecture)
    if hasattr(model.llama, "output"):
        output_layer = model.llama.output
        if hasattr(output_layer, "weight"):
            out_dim, in_dim = output_layer.weight.shape
            new_output = nn.Linear(in_features=in_dim, out_features=after, bias=hasattr(output_layer, "bias") and getattr(output_layer, "bias") is not None)
            with torch.no_grad():
                if out_dim == old_num_tokens:
                    new_output.weight.data[:old_num_tokens, :] = output_layer.weight.data
                    mean_out = output_layer.weight.data.mean(dim=0, keepdim=True)
                    added_for_clusters = after - old_num_tokens
                    new_output.weight.data[old_num_tokens:, :] = mean_out.expand(added_for_clusters, -1)
            new_output.weight.requires_grad = True
            model.llama.output = new_output

    # ── CRITICAL: Patch all cached vocab_size attributes ──────────────────
    # MuMu-LLaMA's internal forward() does: logits.view(-1, self.vocab_size)
    # If vocab_size is stale (32008), it will crash after we expanded to 34197.
    # We force-update every possible location the old size may be cached.
    for obj in [model, model.llama]:
        for attr in ["vocab_size", "n_words", "params"]:
            if hasattr(obj, attr):
                val = getattr(obj, attr)
                if isinstance(val, int) and val == old_num_tokens:
                    setattr(obj, attr, after)
                    print(f"  Patched {obj.__class__.__name__}.{attr}: {old_num_tokens} → {after}")
                elif hasattr(val, "vocab_size") and val.vocab_size == old_num_tokens:
                    val.vocab_size = after
                    print(f"  Patched {obj.__class__.__name__}.{attr}.vocab_size: {old_num_tokens} → {after}")

    # ── CRITICAL: Patch model_args.num_gen_audio_tokens ───────────────────
    # mumu_llama.py line 623 asserts:
    #   self.llama.vocab_size == 32000 + self.model_args.num_gen_audio_tokens
    # After our expansion: vocab_size=34197, so num_gen_audio_tokens must = 2197
    # (original 8 AUD tokens + 2189 cluster tokens we added)
    if hasattr(model, "model_args") and hasattr(model.model_args, "num_gen_audio_tokens"):
        old_val = model.model_args.num_gen_audio_tokens
        model.model_args.num_gen_audio_tokens = after - 32000
        print(f"  Patched model_args.num_gen_audio_tokens: {old_val} → {model.model_args.num_gen_audio_tokens}")


    print(f"  Embedding matrix manually resized: ({old_num_tokens}, {embed_dim}) → ({after}, {embed_dim})")
    print(f"  New rows warm-started with mean embeddings.")
    print("── Done ─────────────────────────────────────────────────────────\n")

    return tokenizer, model


class HierarchicalDataset(Dataset):
    """
    Loads hierarchical_train.jsonl.
    Each sample:
      - Loads the 5-second .wav audio chunk
      - Tokenizes the prompt (masked in labels so model doesn't learn it)
      - Tokenizes the cluster token sequence as the learning target
    """
    def __init__(self, jsonl_path, tokenizer, max_words):
        self.samples = []
        with open(jsonl_path, "r") as f:
            for line in f:
                self.samples.append(json.loads(line))
        self.tokenizer = tokenizer
        self.max_words = max_words
        print(f"  Loaded {len(self.samples)} hierarchical training windows.")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        item     = self.samples[idx]
        audio_path = item["audio_path"]
        prompt     = item["text_prompt"]
        response   = item["text_response"]   # e.g. "<|cluster_8|> <|cluster_12|> <|cluster_4|>"

        # ── Load audio ─────────────────────────────────────────────────────
        try:
            waveform, sr = torchaudio.load(audio_path)
        except Exception:
            # Return a silent dummy if the audio chunk is missing (remote HPC path)
            waveform = torch.zeros(1, SAMPLE_RATE * 5)
            sr       = SAMPLE_RATE

        if sr != SAMPLE_RATE:
            waveform = torchaudio.functional.resample(waveform, orig_freq=sr, new_freq=SAMPLE_RATE)
        audio = torch.mean(waveform, 0)   # mono

        # ── Tokenise ────────────────────────────────────────────────────────
        import llama
        input_with_prompt   = llama.utils.format_prompt(prompt)
        full_input          = input_with_prompt + response

        prompt_ids = torch.tensor(
            self.tokenizer(input_with_prompt).input_ids, dtype=torch.int64
        )
        full_ids = torch.tensor(
            self.tokenizer(full_input).input_ids, dtype=torch.int64
        )

        # Pad or truncate to max_words
        padding = self.max_words - full_ids.shape[0]
        if padding < 0:
            full_ids = full_ids[:self.max_words]
        elif padding > 0:
            full_ids = torch.cat([full_ids, torch.zeros(padding, dtype=torch.int64)])

        # ── PERMANENT FIX: Clamp all token IDs to valid vocab range ─────────
        # Vocab size = len(tokenizer) = 34197, so valid IDs are 0 .. 34196.
        # Any ID >= 34197 would crash CrossEntropyLoss with exactly "34197".
        vocab_size = len(self.tokenizer)
        full_ids = full_ids.clamp(min=0, max=vocab_size - 1)

        # ── Mask labels: only learn the cluster token sequence ──────────────
        # MuMu's internal self.criterion uses ignore_index=0, so we mask
        # prompt tokens with 0 (NOT -100 which would crash the CUDA NLL loss).
        labels = full_ids.clone()
        labels[:len(prompt_ids)] = 0  # mask prompt — MuMu ignores token_id=0

        mask = full_ids.ne(0)

        return full_ids, labels, mask, audio, "Audio", ""


def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # ── Import MuMu native modules ──────────────────────────────────────────
    from llama.mumu_llama import MuMu_LLaMA
    import llama
    from transformers import LlamaTokenizer
    import argparse

    # ── Tokenizer ───────────────────────────────────────────────────────────
    print("Loading LLaMA tokenizer...")
    tokenizer = LlamaTokenizer.from_pretrained(LLAMA_DIR)
    
    # Pre-align tokenizer with the 8 [AUD] tokens MuMu injects internally
    # This prevents ID collision and matrix slicing errors when we add our cluster tokens
    aud_tokens = [f"[AUD{i}]" for i in range(8)]
    tokenizer.add_tokens(aud_tokens, special_tokens=True)

    # ── Model ────────────────────────────────────────────────────────────────
    model_args = argparse.Namespace(
        mert_path="m-a-p/MERT-v1-330M",
        vit_path="google/vit-base-patch16-224",
        vivit_path="google/vivit-b-16x2-kinetics400",
        music_decoder="musicgen",
        music_decoder_path="facebook/musicgen-small",
        max_words=MAX_WORDS,
    )

    print("Loading MuMu-LLaMA model...")
    model = MuMu_LLaMA(
        llama_ckpt_dir=os.path.join(LLAMA_DIR, "7B"),
        llama_tokenizer=LLAMA_DIR,
        model_args=model_args,
        knn_dir="/data/mg546924/llm_beatmap_generator/MuMu-LLaMA/ckpts",
        stage=3,
    )

    print(f"Loading pretrained MuMu checkpoint: {MUMU_CKPT}")
    ckpt = torch.load(MUMU_CKPT, map_location="cpu")
    model.load_state_dict(ckpt, strict=False)
    print("✅ MuMu-LLaMA loaded!")

    # ── STEP 1: Extend tokenizer + model with cluster tokens ─────────────────
    cluster_tokens = load_cluster_tokens(TOKENS_TXT)
    tokenizer, model = extend_tokenizer_and_model(tokenizer, model, cluster_tokens)

    print(f"Transferring model to {torch.cuda.device_count()} GPUs (FP32 params + FP16 autocast)...")
    # Model parameters stay in FP32 — GradScaler requires FP32 params to unscale gradients.
    # The autocast block in the training loop still uses FP16 for fast computation.
    # FP32 model = ~28GB VRAM, well within the A40's 45GB limit.
    model = model.cuda()

    # Enable native PyTorch DataParallel across all available Slurm GPUs
    n_gpus = torch.cuda.device_count()
    if n_gpus > 1:
        print(f"🔥 Automatic DataParallel Enabled across {n_gpus} GPUs! 🔥")
        model = torch.nn.DataParallel(model)

    print("Model initialized and ready.")
    # ── STEP 2: Dataset ──────────────────────────────────────────────────────
    print("Loading hierarchical SFT dataset...")
    full_dataset = HierarchicalDataset(DATASET_JSONL, tokenizer, MAX_WORDS)

    val_size   = max(1, int(len(full_dataset) * 0.05))
    train_size = len(full_dataset) - val_size
    train_dataset, val_dataset = torch.utils.data.random_split(
        full_dataset, [train_size, val_size]
    )
    print(f"  Train: {train_size} | Val: {val_size}")

    effective_batch_size = BATCH_SIZE * max(1, torch.cuda.device_count())

    train_loader = DataLoader(
        train_dataset,
        batch_size=effective_batch_size,
        shuffle=True,
        drop_last=True
    )
    val_loader   = DataLoader(val_dataset,   batch_size=BATCH_SIZE, shuffle=False, num_workers=0)

    # ── STEP 3: Optimizer + GradScaler ──────────────────────────────────────
    # Only update the new cluster token embeddings + LoRA/trainable layers
    optimizer = torch.optim.AdamW(
        filter(lambda p: p.requires_grad, model.parameters()),
        lr=LR, weight_decay=0.05
    )
    # GradScaler prevents NaN loss from FP16 overflow — standard for mixed precision
    scaler = torch.cuda.amp.GradScaler()

    # ── STEP 4: Training Loop ─────────────────────────────────────────────────
    loss_log = []
    print(f"\n{'='*60}")
    print("Starting Hierarchical Director Training")
    print(f"  Epochs     : {NUM_EPOCHS}")
    print(f"  Batch size : {BATCH_SIZE}")
    print(f"  LR         : {LR}")
    print(f"  Cluster tokens in vocab: {len(cluster_tokens)}")
    print(f"{'='*60}\n")

    for epoch in range(NUM_EPOCHS):
        model.train()
        epoch_loss, num_batches = 0.0, 0

        pbar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{NUM_EPOCHS}")
        for batch_idx, (examples, labels, mask, audio, modality, caption) in enumerate(pbar):
            examples = examples.cuda().contiguous()
            labels   = labels.cuda().contiguous()
            audio    = audio.cuda().contiguous()

            optimizer.zero_grad()
            try:
                with torch.cuda.amp.autocast(dtype=torch.float16):
                    c_loss, m_loss = model(examples, labels, audios=audio, music_caption=None)

                    # If multiple GPUs are used, average the scattered loss arrays
                    if torch.cuda.device_count() > 1:
                        c_loss = c_loss.mean()
                        m_loss = m_loss.mean()

                    loss = c_loss + m_loss

                # GradScaler: scales loss to prevent FP16 underflow/overflow → no NaN
                scaler.scale(loss).backward()
                scaler.unscale_(optimizer)
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                scaler.step(optimizer)
                scaler.update()

                loss_val = loss.item()
                if not (loss_val != loss_val):  # skip NaN batches from the average
                    epoch_loss  += loss_val
                    num_batches += 1
                    pbar.set_postfix({"loss": f"{epoch_loss/num_batches:.4f}"})

                # Periodic VRAM defrag
                del c_loss, m_loss, loss
                if batch_idx > 0 and batch_idx % 50 == 0:
                    torch.cuda.empty_cache()

            except Exception as e:
                import traceback
                print(f"\n  [SKIP] batch {batch_idx}: {e}\n{traceback.format_exc()}\n")
                continue

        avg_train_loss = epoch_loss / max(num_batches, 1)

        # ── Validation ───────────────────────────────────────────────────────
        model.eval()
        val_loss, val_batches = 0.0, 0
        with torch.no_grad():
            for examples, labels, mask, audio, modality, caption in val_loader:
                examples = examples.cuda()
                labels   = labels.cuda()
                audio    = audio.cuda()
                try:
                    with torch.cuda.amp.autocast(dtype=torch.float16):
                        c_loss, m_loss = model(examples, labels, audios=audio, music_caption=None)
                        val_loss   += (c_loss + m_loss).item()
                        val_batches += 1
                except Exception as e:
                    import traceback
                    print(f"  [VAL SKIP]: {e}\n{traceback.format_exc()}")
                    continue

        avg_val_loss = val_loss / max(val_batches, 1)
        print(f"\n📊 Epoch {epoch+1}/{NUM_EPOCHS} — Train: {avg_train_loss:.4f} | Val: {avg_val_loss:.4f}\n")
        loss_log.append({"epoch": epoch+1, "train_loss": avg_train_loss, "val_loss": avg_val_loss})

    # ── Save ONE final checkpoint after all epochs complete ───────────────────
    # (No per-epoch saves — each checkpoint is ~14GB, 5 epochs = 70GB wasted!)
    ckpt_out = os.path.join(OUTPUT_DIR, "checkpoint_final.pth")
    torch.save(model.state_dict(), ckpt_out)
    tokenizer.save_pretrained(os.path.join(OUTPUT_DIR, "tokenizer"))
    print(f"  💾 Final checkpoint saved: {ckpt_out}")

    # ── Save loss log ─────────────────────────────────────────────────────────
    log_path = os.path.join(OUTPUT_DIR, "training_log.csv")
    with open(log_path, "w", newline="") as f:
        writer = csv_mod.writer(f)
        writer.writerow(["epoch", "train_loss", "val_loss"])
        for entry in loss_log:
            writer.writerow([entry["epoch"], f"{entry['train_loss']:.4f}", f"{entry['val_loss']:.4f}"])

    print(f"\n✅ Hierarchical Director Training Complete!")
    print(f"   Model saved to : {ckpt_out}")
    print(f"   Tokenizer saved: {OUTPUT_DIR}/tokenizer")
    print(f"   Loss log       : {log_path}")


if __name__ == "__main__":
    main()
